recObj= audiorecorder;
a=arduino()
disp('start')
recordblocking(recObj,10)
disp('end')
writeDigitalPin(a,'D3',0)
writeDigitalPin(a,'D5',0)
writeDigitalPin(a,'D6',0)
writeDigitalPin(a,'D9',0)
y=getaudiodata(recObj)
plot(abs(y))
disp(y)
for i=1000:length(y)
    if abs(y(i))<=0.0010
        writeDigitalPin(a,'D3',1)
        pause(0.1)
        writeDigitalPin(a,'D3',0)
        disp('1')
    elseif 0.0010<abs(y(i))<=0.0050
        writeDigitalPin(a,'D3',1)
        writeDigitalPin(a,'D5',1)
        pause(0.1)
        writeDigitalPin(a,'D3',0)
        writeDigitalPin(a,'D5',0)
        disp('2')
    elseif 0.0050<abs(y(i))<=0.0125
        writeDigitalPin(a,'D3',1)
        writeDigitalPin(a,'D5',1)
        writeDigitalPin(a,'D6',1)
        pause(0.1)
        writeDigitalPin(a,'D3',0)
        writeDigitalPin(a,'D5',0)
        writeDigitalPin(a,'D6',0)
        disp('3')
    elseif 0.0125<abs(y(i))
        writeDigitalPin(a,'D3',1)
        writeDigitalPin(a,'D5',1)
        writeDigitalPin(a,'D6',1)
        writeDigitalPin(a,'D9',1)
        pause(0.1)
        writeDigitalPin(a,'D3',0)
        writeDigitalPin(a,'D5',0)
        writeDigitalPin(a,'D6',0)
        writeDigitalPin(a,'D9',0)
        disp('4')
    end
end
